### ISSUE TITLE
Upload page issue!

### ISSUE THREAD

**Issue by GilloDaby** [Nsttt/BDOScoreAnalyzer#1]
Hey! I know you don't work anymore on this but I really like the idea of uploading wars sheet. I need more information to understand how this work please!  I make work the page in a private website and now when I upload I got a error page /upload (PAGE NOT FOUND)

Thanks for answering me!

**Comment by Nsttt** [comment]
Hello! Thanks for the reminder that I didn't deploy this one yet.

I just did and tested everything. For me it appears to be working just fine. You can use my instance if you like [here](http://scores.nstlopez.com). Also would appreciate a star if you enjoy the app. 😄 

Best regards.

**Comment by GilloDaby** [comment]
Hey your website is down for the moment! May you fix this ?

https://scores.nstlopez.com/

**Comment by Nsttt** [comment]
It does not work through https, since I don't have an ssl cert atm. Try http://scores.nstlopez.com
